import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Welcome to my Elearning site&nbsp;
          </p>
        </div>
        <div className={styles.grid}>

          
          
          <a
            href="/learn/nextjs"
            className={styles.card}>
            <h2 className={inter.className}>
              Learn NextJS &rarr;</h2></a>


          <a
            href="/learn/react"
            className={styles.card}>
            <h2 className={inter.className}>
              Learn React &rarr;</h2></a>

          <a
            href="/learn/angular"
            className={styles.card}>
            <h2 className={inter.className}>
              Learn Angular &rarr;</h2></a>

          <a
            href="/learn/vue"
            className={styles.card}>
            <h2 className={inter.className}>
              Learn Vue &rarr;</h2></a>
        </div>
      </main>
    </>
  )
}
